### ISSUE TITLE
StrawberryShake: Mutation containing input with a lowercase-named enum type fails generate code

### ISSUE THREAD

**Issue by treet** [ChilliCream/hotchocolate#3704]
Code generation fails when I try to generate code for a mutation containing a lowercase-named enum type. If I rename **jobstatus** to **JobStatus** in the schema below, `dotnet build` succeeds and code is generated.

This feels like very strange behavior, is this a bug or am I going crazy?

This makes StrawberryShake unusable with e.g. Hasura (https://hasura.io/) which always use lowercase for all GraphQL types.

**Error message**
```sh
$ dotnet build
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : error SS0006: The given key 'StrawberryShake.RuntimeType' was not present in the dictionary.

Build FAILED.

CSC : error SS0006: The given key 'StrawberryShake.RuntimeType' was not present in the dictionary.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.85
```

**To Reproduce**

In a new project, attempt to generate code with the following schema and mutation. This is not my original schema, but the minimum schema I could come up with that produces the error.

InsertJobs.graphql

```graphql
mutation InsertJobs($object: JobInput!) {
    insertJobs(object: $object)
}
```

schema.graphql
```graphql
schema {
  query: QueryRoot
  mutation: MutationRoot
}

enum jobstatus {
  Started
  Processing
  Finished
}

type Job {
  status: jobstatus!
}

input JobInput {
  status: jobstatus!
}

type InsertJobsResponse {
  returning: Job!
}

type QueryRoot {
  jobs(): [Job!]!
}

type MutationRoot {
  insertJobs(object: JobInput!): Boolean!
}
```

**Desktop (please complete the following information):**
 - OS: Win10 (WSL)
 - Version: StrawberryShake.CodeGeneration.CSharp.Analyzers 12.0.0-preview.3

**Comment by PascalSenn** [comment]
This is fixed in 12.5

**Comment by gerwim** [comment]
@PascalSenn This issue is still present in 12.7.0.

Reproduction:

```
mutation InsertProtocol ($name: String!, $type: ProtocolTypes_enum!, $fileUrl: String!) {
    insert_protocols_one(object: {
        name: $name,
        type: $type,
        fileUrl: $fileUrl,
    })
    {
        id
    }
}
```

Broken schema (the working schema can be found below):

```
# This file was generated based on ".graphqlconfig". Do not edit manually.

schema {
    query: query_root
    mutation: mutation_root
    subscription: subscription_root
}

"whether this query should be cached (Hasura Cloud only)"
directive @cached(
    "refresh the cache entry"
    refresh: Boolean! = false,
    "measured in seconds"
    ttl: Int! = 60
) on QUERY

"columns and relationships of \"events\""
type events {
    id: uuid!
    name: String!
}

"aggregated selection of \"events\""
type events_aggregate {
    aggregate: events_aggregate_fields
    nodes: [events!]!
}

"aggregate fields of \"events\""
type events_aggregate_fields {
    count(columns: [events_select_column!], distinct: Boolean): Int!
    max: events_max_fields
    min: events_min_fields
}

"aggregate max on columns"
type events_max_fields {
    id: uuid
    name: String
}

"aggregate min on columns"
type events_min_fields {
    id: uuid
    name: String
}

"response of any mutation on the table \"events\""
type events_mutation_response {
    "number of rows affected by the mutation"
    affected_rows: Int!
    "data from the rows affected by the mutation"
    returning: [events!]!
}

"mutation root"
type mutation_root {
    "delete data from the table: \"events\""
    delete_events(
        "filter the rows which have to be deleted"
        where: events_bool_exp!
    ): events_mutation_response
    "delete single row from the table: \"events\""
    delete_events_by_pk(id: uuid!): events
    "delete data from the table: \"protocolTypes\""
    delete_protocolTypes(
        "filter the rows which have to be deleted"
        where: protocolTypes_bool_exp!
    ): protocolTypes_mutation_response
    "delete single row from the table: \"protocolTypes\""
    delete_protocolTypes_by_pk(type: String!): protocolTypes
    "delete data from the table: \"protocols\""
    delete_protocols(
        "filter the rows which have to be deleted"
        where: protocols_bool_exp!
    ): protocols_mutation_response
    "delete single row from the table: \"protocols\""
    delete_protocols_by_pk(id: uuid!): protocols
    "insert data into the table: \"events\""
    insert_events(
        "the rows to be inserted"
        objects: [events_insert_input!]!,
        "upsert condition"
        on_conflict: events_on_conflict
    ): events_mutation_response
    "insert a single row into the table: \"events\""
    insert_events_one(
        "the row to be inserted"
        object: events_insert_input!,
        "upsert condition"
        on_conflict: events_on_conflict
    ): events
    "insert data into the table: \"protocolTypes\""
    insert_protocolTypes(
        "the rows to be inserted"
        objects: [protocolTypes_insert_input!]!,
        "upsert condition"
        on_conflict: protocolTypes_on_conflict
    ): protocolTypes_mutation_response
    "insert a single row into the table: \"protocolTypes\""
    insert_protocolTypes_one(
        "the row to be inserted"
        object: protocolTypes_insert_input!,
        "upsert condition"
        on_conflict: protocolTypes_on_conflict
    ): protocolTypes
    "insert data into the table: \"protocols\""
    insert_protocols(
        "the rows to be inserted"
        objects: [protocols_insert_input!]!,
        "upsert condition"
        on_conflict: protocols_on_conflict
    ): protocols_mutation_response
    "insert a single row into the table: \"protocols\""
    insert_protocols_one(
        "the row to be inserted"
        object: protocols_insert_input!,
        "upsert condition"
        on_conflict: protocols_on_conflict
    ): protocols
    "update data of the table: \"events\""
    update_events(
        "sets the columns of the filtered rows to the given values"
        _set: events_set_input,
        "filter the rows which have to be updated"
        where: events_bool_exp!
    ): events_mutation_response
    "update single row of the table: \"events\""
    update_events_by_pk(
        "sets the columns of the filtered rows to the given values"
        _set: events_set_input,
        pk_columns: events_pk_columns_input!
    ): events
    "update data of the table: \"protocolTypes\""
    update_protocolTypes(
        "sets the columns of the filtered rows to the given values"
        _set: protocolTypes_set_input,
        "filter the rows which have to be updated"
        where: protocolTypes_bool_exp!
    ): protocolTypes_mutation_response
    "update single row of the table: \"protocolTypes\""
    update_protocolTypes_by_pk(
        "sets the columns of the filtered rows to the given values"
        _set: protocolTypes_set_input,
        pk_columns: protocolTypes_pk_columns_input!
    ): protocolTypes
    "update data of the table: \"protocols\""
    update_protocols(
        "sets the columns of the filtered rows to the given values"
        _set: protocols_set_input,
        "filter the rows which have to be updated"
        where: protocols_bool_exp!
    ): protocols_mutation_response
    "update single row of the table: \"protocols\""
    update_protocols_by_pk(
        "sets the columns of the filtered rows to the given values"
        _set: protocols_set_input,
        pk_columns: protocols_pk_columns_input!
    ): protocols
}

"columns and relationships of \"protocolTypes\""
type protocolTypes {
    type: String!
}

"aggregated selection of \"protocolTypes\""
type protocolTypes_aggregate {
    aggregate: protocolTypes_aggregate_fields
    nodes: [protocolTypes!]!
}

"aggregate fields of \"protocolTypes\""
type protocolTypes_aggregate_fields {
    count(columns: [protocolTypes_select_column!], distinct: Boolean): Int!
    max: protocolTypes_max_fields
    min: protocolTypes_min_fields
}

"aggregate max on columns"
type protocolTypes_max_fields {
    type: String
}

"aggregate min on columns"
type protocolTypes_min_fields {
    type: String
}

"response of any mutation on the table \"protocolTypes\""
type protocolTypes_mutation_response {
    "number of rows affected by the mutation"
    affected_rows: Int!
    "data from the rows affected by the mutation"
    returning: [protocolTypes!]!
}

"columns and relationships of \"protocols\""
type protocols {
    fileUrl: String!
    id: uuid!
    name: String!
    type: protocolTypes_enum!
}

"aggregated selection of \"protocols\""
type protocols_aggregate {
    aggregate: protocols_aggregate_fields
    nodes: [protocols!]!
}

"aggregate fields of \"protocols\""
type protocols_aggregate_fields {
    count(columns: [protocols_select_column!], distinct: Boolean): Int!
    max: protocols_max_fields
    min: protocols_min_fields
}

"aggregate max on columns"
type protocols_max_fields {
    fileUrl: String
    id: uuid
    name: String
}

"aggregate min on columns"
type protocols_min_fields {
    fileUrl: String
    id: uuid
    name: String
}

"response of any mutation on the table \"protocols\""
type protocols_mutation_response {
    "number of rows affected by the mutation"
    affected_rows: Int!
    "data from the rows affected by the mutation"
    returning: [protocols!]!
}

type query_root {
    "fetch data from the table: \"events\""
    events(
        "distinct select on columns"
        distinct_on: [events_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [events_order_by!],
        "filter the rows returned"
        where: events_bool_exp
    ): [events!]!
    "fetch aggregated fields from the table: \"events\""
    events_aggregate(
        "distinct select on columns"
        distinct_on: [events_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [events_order_by!],
        "filter the rows returned"
        where: events_bool_exp
    ): events_aggregate!
    "fetch data from the table: \"events\" using primary key columns"
    events_by_pk(id: uuid!): events
    "fetch data from the table: \"protocolTypes\""
    protocolTypes(
        "distinct select on columns"
        distinct_on: [protocolTypes_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocolTypes_order_by!],
        "filter the rows returned"
        where: protocolTypes_bool_exp
    ): [protocolTypes!]!
    "fetch aggregated fields from the table: \"protocolTypes\""
    protocolTypes_aggregate(
        "distinct select on columns"
        distinct_on: [protocolTypes_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocolTypes_order_by!],
        "filter the rows returned"
        where: protocolTypes_bool_exp
    ): protocolTypes_aggregate!
    "fetch data from the table: \"protocolTypes\" using primary key columns"
    protocolTypes_by_pk(type: String!): protocolTypes
    "fetch data from the table: \"protocols\""
    protocols(
        "distinct select on columns"
        distinct_on: [protocols_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocols_order_by!],
        "filter the rows returned"
        where: protocols_bool_exp
    ): [protocols!]!
    "fetch aggregated fields from the table: \"protocols\""
    protocols_aggregate(
        "distinct select on columns"
        distinct_on: [protocols_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocols_order_by!],
        "filter the rows returned"
        where: protocols_bool_exp
    ): protocols_aggregate!
    "fetch data from the table: \"protocols\" using primary key columns"
    protocols_by_pk(id: uuid!): protocols
}

type subscription_root {
    "fetch data from the table: \"events\""
    events(
        "distinct select on columns"
        distinct_on: [events_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [events_order_by!],
        "filter the rows returned"
        where: events_bool_exp
    ): [events!]!
    "fetch aggregated fields from the table: \"events\""
    events_aggregate(
        "distinct select on columns"
        distinct_on: [events_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [events_order_by!],
        "filter the rows returned"
        where: events_bool_exp
    ): events_aggregate!
    "fetch data from the table: \"events\" using primary key columns"
    events_by_pk(id: uuid!): events
    "fetch data from the table: \"protocolTypes\""
    protocolTypes(
        "distinct select on columns"
        distinct_on: [protocolTypes_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocolTypes_order_by!],
        "filter the rows returned"
        where: protocolTypes_bool_exp
    ): [protocolTypes!]!
    "fetch aggregated fields from the table: \"protocolTypes\""
    protocolTypes_aggregate(
        "distinct select on columns"
        distinct_on: [protocolTypes_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocolTypes_order_by!],
        "filter the rows returned"
        where: protocolTypes_bool_exp
    ): protocolTypes_aggregate!
    "fetch data from the table: \"protocolTypes\" using primary key columns"
    protocolTypes_by_pk(type: String!): protocolTypes
    "fetch data from the table: \"protocols\""
    protocols(
        "distinct select on columns"
        distinct_on: [protocols_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocols_order_by!],
        "filter the rows returned"
        where: protocols_bool_exp
    ): [protocols!]!
    "fetch aggregated fields from the table: \"protocols\""
    protocols_aggregate(
        "distinct select on columns"
        distinct_on: [protocols_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocols_order_by!],
        "filter the rows returned"
        where: protocols_bool_exp
    ): protocols_aggregate!
    "fetch data from the table: \"protocols\" using primary key columns"
    protocols_by_pk(id: uuid!): protocols
}

"unique or primary key constraints on table \"events\""
enum events_constraint {
    "unique or primary key constraint"
    events_name_key
    "unique or primary key constraint"
    events_pkey
}

"select columns of table \"events\""
enum events_select_column {
    "column name"
    id
    "column name"
    name
}

"update columns of table \"events\""
enum events_update_column {
    "column name"
    id
    "column name"
    name
}

"column ordering options"
enum order_by {
    "in ascending order, nulls last"
    asc
    "in ascending order, nulls first"
    asc_nulls_first
    "in ascending order, nulls last"
    asc_nulls_last
    "in descending order, nulls first"
    desc
    "in descending order, nulls first"
    desc_nulls_first
    "in descending order, nulls last"
    desc_nulls_last
}

"unique or primary key constraints on table \"protocolTypes\""
enum protocolTypes_constraint {
    "unique or primary key constraint"
    protocolTypes_pkey
}

enum protocolTypes_enum {
    Item1
    Item2
    Item3
}

"select columns of table \"protocolTypes\""
enum protocolTypes_select_column {
    "column name"
    type
}

"update columns of table \"protocolTypes\""
enum protocolTypes_update_column {
    "column name"
    type
}

"unique or primary key constraints on table \"protocols\""
enum protocols_constraint {
    "unique or primary key constraint"
    protocols_pkey
}

"select columns of table \"protocols\""
enum protocols_select_column {
    "column name"
    fileUrl
    "column name"
    id
    "column name"
    name
    "column name"
    type
}

"update columns of table \"protocols\""
enum protocols_update_column {
    "column name"
    fileUrl
    "column name"
    id
    "column name"
    name
    "column name"
    type
}

scalar uuid

"Boolean expression to compare columns of type \"String\". All fields are combined with logical 'AND'."
input String_comparison_exp {
    _eq: String
    _gt: String
    _gte: String
    "does the column match the given case-insensitive pattern"
    _ilike: String
    _in: [String!]
    "does the column match the given POSIX regular expression, case insensitive"
    _iregex: String
    _is_null: Boolean
    "does the column match the given pattern"
    _like: String
    _lt: String
    _lte: String
    _neq: String
    "does the column NOT match the given case-insensitive pattern"
    _nilike: String
    _nin: [String!]
    "does the column NOT match the given POSIX regular expression, case insensitive"
    _niregex: String
    "does the column NOT match the given pattern"
    _nlike: String
    "does the column NOT match the given POSIX regular expression, case sensitive"
    _nregex: String
    "does the column NOT match the given SQL regular expression"
    _nsimilar: String    "does the column match the given POSIX regular expression, case sensitive"
    _regex: String
    "does the column match the given SQL regular expression"
    _similar: String
}

"Boolean expression to filter rows from the table \"events\". All fields are combined with a logical 'AND'."
input events_bool_exp {
    _and: [events_bool_exp!]
    _not: events_bool_exp
    _or: [events_bool_exp!]
    id: uuid_comparison_exp
    name: String_comparison_exp
}

"input type for inserting data into table \"events\""
input events_insert_input {
    id: uuid
    name: String
}

"on_conflict condition type for table \"events\""
input events_on_conflict {
    constraint: events_constraint!
    update_columns: [events_update_column!]! = []
    where: events_bool_exp
}

"Ordering options when selecting data from \"events\"."
input events_order_by {
    id: order_by
    name: order_by
}

"primary key columns input for table: events"
input events_pk_columns_input {
    id: uuid!
}

"input type for updating data in table \"events\""
input events_set_input {
    id: uuid
    name: String
}

"Boolean expression to filter rows from the table \"protocolTypes\". All fields are combined with a logical 'AND'."
input protocolTypes_bool_exp {
    _and: [protocolTypes_bool_exp!]
    _not: protocolTypes_bool_exp
    _or: [protocolTypes_bool_exp!]
    type: String_comparison_exp
}

"Boolean expression to compare columns of type \"protocolTypes_enum\". All fields are combined with logical 'AND'."
input protocolTypes_enum_comparison_exp {
    _eq: protocolTypes_enum
    _in: [protocolTypes_enum!]
    _is_null: Boolean
    _neq: protocolTypes_enum
    _nin: [protocolTypes_enum!]
}

"input type for inserting data into table \"protocolTypes\""
input protocolTypes_insert_input {
    type: String
}

"on_conflict condition type for table \"protocolTypes\""
input protocolTypes_on_conflict {
    constraint: protocolTypes_constraint!
    update_columns: [protocolTypes_update_column!]! = []
    where: protocolTypes_bool_exp
}

"Ordering options when selecting data from \"protocolTypes\"."
input protocolTypes_order_by {
    type: order_by
}

"primary key columns input for table: protocolTypes"
input protocolTypes_pk_columns_input {
    type: String!
}

"input type for updating data in table \"protocolTypes\""
input protocolTypes_set_input {
    type: String
}

"Boolean expression to filter rows from the table \"protocols\". All fields are combined with a logical 'AND'."
input protocols_bool_exp {
    _and: [protocols_bool_exp!]
    _not: protocols_bool_exp
    _or: [protocols_bool_exp!]
    fileUrl: String_comparison_exp
    id: uuid_comparison_exp
    name: String_comparison_exp
    type: protocolTypes_enum_comparison_exp
}

"input type for inserting data into table \"protocols\""
input protocols_insert_input {
    fileUrl: String
    id: uuid
    name: String
    type: protocolTypes_enum
}

"on_conflict condition type for table \"protocols\""
input protocols_on_conflict {
    constraint: protocols_constraint!
    update_columns: [protocols_update_column!]! = []
    where: protocols_bool_exp
}

"Ordering options when selecting data from \"protocols\"."
input protocols_order_by {
    fileUrl: order_by
    id: order_by
    name: order_by
    type: order_by
}

"primary key columns input for table: protocols"
input protocols_pk_columns_input {
    id: uuid!
}

"input type for updating data in table \"protocols\""
input protocols_set_input {
    fileUrl: String
    id: uuid
    name: String
    type: protocolTypes_enum
}

"Boolean expression to compare columns of type \"uuid\". All fields are combined with logical 'AND'."
input uuid_comparison_exp {
    _eq: uuid
    _gt: uuid
    _gte: uuid
    _in: [uuid!]
    _is_null: Boolean
    _lt: uuid
    _lte: uuid
    _neq: uuid
    _nin: [uuid!]
}
```
Working schema (uppercased `protocolTypes_enum` to `ProtocolTypes_enum`):
```
# This file was generated based on ".graphqlconfig". Do not edit manually.

schema {
    query: query_root
    mutation: mutation_root
    subscription: subscription_root
}

"whether this query should be cached (Hasura Cloud only)"
directive @cached(
    "refresh the cache entry"
    refresh: Boolean! = false,
    "measured in seconds"
    ttl: Int! = 60
) on QUERY

"columns and relationships of \"events\""
type events {
    id: uuid!
    name: String!
}

"aggregated selection of \"events\""
type events_aggregate {
    aggregate: events_aggregate_fields
    nodes: [events!]!
}

"aggregate fields of \"events\""
type events_aggregate_fields {
    count(columns: [events_select_column!], distinct: Boolean): Int!
    max: events_max_fields
    min: events_min_fields
}

"aggregate max on columns"
type events_max_fields {
    id: uuid
    name: String
}

"aggregate min on columns"
type events_min_fields {
    id: uuid
    name: String
}

"response of any mutation on the table \"events\""
type events_mutation_response {
    "number of rows affected by the mutation"
    affected_rows: Int!
    "data from the rows affected by the mutation"
    returning: [events!]!
}

"mutation root"
type mutation_root {
    "delete data from the table: \"events\""
    delete_events(
        "filter the rows which have to be deleted"
        where: events_bool_exp!
    ): events_mutation_response
    "delete single row from the table: \"events\""
    delete_events_by_pk(id: uuid!): events
    "delete data from the table: \"protocolTypes\""
    delete_protocolTypes(
        "filter the rows which have to be deleted"
        where: protocolTypes_bool_exp!
    ): protocolTypes_mutation_response
    "delete single row from the table: \"protocolTypes\""
    delete_protocolTypes_by_pk(type: String!): protocolTypes
    "delete data from the table: \"protocols\""
    delete_protocols(
        "filter the rows which have to be deleted"
        where: protocols_bool_exp!
    ): protocols_mutation_response
    "delete single row from the table: \"protocols\""
    delete_protocols_by_pk(id: uuid!): protocols
    "insert data into the table: \"events\""
    insert_events(
        "the rows to be inserted"
        objects: [events_insert_input!]!,
        "upsert condition"
        on_conflict: events_on_conflict
    ): events_mutation_response
    "insert a single row into the table: \"events\""
    insert_events_one(
        "the row to be inserted"
        object: events_insert_input!,
        "upsert condition"
        on_conflict: events_on_conflict
    ): events
    "insert data into the table: \"protocolTypes\""
    insert_protocolTypes(
        "the rows to be inserted"
        objects: [protocolTypes_insert_input!]!,
        "upsert condition"
        on_conflict: protocolTypes_on_conflict
    ): protocolTypes_mutation_response
    "insert a single row into the table: \"protocolTypes\""
    insert_protocolTypes_one(
        "the row to be inserted"
        object: protocolTypes_insert_input!,
        "upsert condition"
        on_conflict: protocolTypes_on_conflict
    ): protocolTypes
    "insert data into the table: \"protocols\""
    insert_protocols(
        "the rows to be inserted"
        objects: [protocols_insert_input!]!,
        "upsert condition"
        on_conflict: protocols_on_conflict
    ): protocols_mutation_response
    "insert a single row into the table: \"protocols\""
    insert_protocols_one(
        "the row to be inserted"
        object: protocols_insert_input!,
        "upsert condition"
        on_conflict: protocols_on_conflict
    ): protocols
    "update data of the table: \"events\""
    update_events(
        "sets the columns of the filtered rows to the given values"
        _set: events_set_input,
        "filter the rows which have to be updated"
        where: events_bool_exp!
    ): events_mutation_response
    "update single row of the table: \"events\""
    update_events_by_pk(
        "sets the columns of the filtered rows to the given values"
        _set: events_set_input,
        pk_columns: events_pk_columns_input!
    ): events
    "update data of the table: \"protocolTypes\""
    update_protocolTypes(
        "sets the columns of the filtered rows to the given values"
        _set: protocolTypes_set_input,
        "filter the rows which have to be updated"
        where: protocolTypes_bool_exp!
    ): protocolTypes_mutation_response
    "update single row of the table: \"protocolTypes\""
    update_protocolTypes_by_pk(
        "sets the columns of the filtered rows to the given values"
        _set: protocolTypes_set_input,
        pk_columns: protocolTypes_pk_columns_input!
    ): protocolTypes
    "update data of the table: \"protocols\""
    update_protocols(
        "sets the columns of the filtered rows to the given values"
        _set: protocols_set_input,
        "filter the rows which have to be updated"
        where: protocols_bool_exp!
    ): protocols_mutation_response
    "update single row of the table: \"protocols\""
    update_protocols_by_pk(
        "sets the columns of the filtered rows to the given values"
        _set: protocols_set_input,
        pk_columns: protocols_pk_columns_input!
    ): protocols
}

"columns and relationships of \"protocolTypes\""
type protocolTypes {
    type: String!
}

"aggregated selection of \"protocolTypes\""
type protocolTypes_aggregate {
    aggregate: protocolTypes_aggregate_fields
    nodes: [protocolTypes!]!
}

"aggregate fields of \"protocolTypes\""
type protocolTypes_aggregate_fields {
    count(columns: [protocolTypes_select_column!], distinct: Boolean): Int!
    max: protocolTypes_max_fields
    min: protocolTypes_min_fields
}

"aggregate max on columns"
type protocolTypes_max_fields {
    type: String
}

"aggregate min on columns"
type protocolTypes_min_fields {
    type: String
}

"response of any mutation on the table \"protocolTypes\""
type protocolTypes_mutation_response {
    "number of rows affected by the mutation"
    affected_rows: Int!
    "data from the rows affected by the mutation"
    returning: [protocolTypes!]!
}

"columns and relationships of \"protocols\""
type protocols {
    fileUrl: String!
    id: uuid!
    name: String!
    type: ProtocolTypes_enum!
}

"aggregated selection of \"protocols\""
type protocols_aggregate {
    aggregate: protocols_aggregate_fields
    nodes: [protocols!]!
}

"aggregate fields of \"protocols\""
type protocols_aggregate_fields {
    count(columns: [protocols_select_column!], distinct: Boolean): Int!
    max: protocols_max_fields
    min: protocols_min_fields
}

"aggregate max on columns"
type protocols_max_fields {
    fileUrl: String
    id: uuid
    name: String
}

"aggregate min on columns"
type protocols_min_fields {
    fileUrl: String
    id: uuid
    name: String
}

"response of any mutation on the table \"protocols\""
type protocols_mutation_response {
    "number of rows affected by the mutation"
    affected_rows: Int!
    "data from the rows affected by the mutation"
    returning: [protocols!]!
}

type query_root {
    "fetch data from the table: \"events\""
    events(
        "distinct select on columns"
        distinct_on: [events_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [events_order_by!],
        "filter the rows returned"
        where: events_bool_exp
    ): [events!]!
    "fetch aggregated fields from the table: \"events\""
    events_aggregate(
        "distinct select on columns"
        distinct_on: [events_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [events_order_by!],
        "filter the rows returned"
        where: events_bool_exp
    ): events_aggregate!
    "fetch data from the table: \"events\" using primary key columns"
    events_by_pk(id: uuid!): events
    "fetch data from the table: \"protocolTypes\""
    protocolTypes(
        "distinct select on columns"
        distinct_on: [protocolTypes_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocolTypes_order_by!],
        "filter the rows returned"
        where: protocolTypes_bool_exp
    ): [protocolTypes!]!
    "fetch aggregated fields from the table: \"protocolTypes\""
    protocolTypes_aggregate(
        "distinct select on columns"
        distinct_on: [protocolTypes_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocolTypes_order_by!],
        "filter the rows returned"
        where: protocolTypes_bool_exp
    ): protocolTypes_aggregate!
    "fetch data from the table: \"protocolTypes\" using primary key columns"
    protocolTypes_by_pk(type: String!): protocolTypes
    "fetch data from the table: \"protocols\""
    protocols(
        "distinct select on columns"
        distinct_on: [protocols_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocols_order_by!],
        "filter the rows returned"
        where: protocols_bool_exp
    ): [protocols!]!
    "fetch aggregated fields from the table: \"protocols\""
    protocols_aggregate(
        "distinct select on columns"
        distinct_on: [protocols_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocols_order_by!],
        "filter the rows returned"
        where: protocols_bool_exp
    ): protocols_aggregate!
    "fetch data from the table: \"protocols\" using primary key columns"
    protocols_by_pk(id: uuid!): protocols
}

type subscription_root {
    "fetch data from the table: \"events\""
    events(
        "distinct select on columns"
        distinct_on: [events_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [events_order_by!],
        "filter the rows returned"
        where: events_bool_exp
    ): [events!]!
    "fetch aggregated fields from the table: \"events\""
    events_aggregate(
        "distinct select on columns"
        distinct_on: [events_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [events_order_by!],
        "filter the rows returned"
        where: events_bool_exp
    ): events_aggregate!
    "fetch data from the table: \"events\" using primary key columns"
    events_by_pk(id: uuid!): events
    "fetch data from the table: \"protocolTypes\""
    protocolTypes(
        "distinct select on columns"
        distinct_on: [protocolTypes_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocolTypes_order_by!],
        "filter the rows returned"
        where: protocolTypes_bool_exp
    ): [protocolTypes!]!
    "fetch aggregated fields from the table: \"protocolTypes\""
    protocolTypes_aggregate(
        "distinct select on columns"
        distinct_on: [protocolTypes_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocolTypes_order_by!],
        "filter the rows returned"
        where: protocolTypes_bool_exp
    ): protocolTypes_aggregate!
    "fetch data from the table: \"protocolTypes\" using primary key columns"
    protocolTypes_by_pk(type: String!): protocolTypes
    "fetch data from the table: \"protocols\""
    protocols(
        "distinct select on columns"
        distinct_on: [protocols_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocols_order_by!],
        "filter the rows returned"
        where: protocols_bool_exp
    ): [protocols!]!
    "fetch aggregated fields from the table: \"protocols\""
    protocols_aggregate(
        "distinct select on columns"
        distinct_on: [protocols_select_column!],
        "limit the number of rows returned"
        limit: Int,
        "skip the first n rows. Use only with order_by"
        offset: Int,
        "sort the rows by one or more columns"
        order_by: [protocols_order_by!],
        "filter the rows returned"
        where: protocols_bool_exp
    ): protocols_aggregate!
    "fetch data from the table: \"protocols\" using primary key columns"
    protocols_by_pk(id: uuid!): protocols
}

"unique or primary key constraints on table \"events\""
enum events_constraint {
    "unique or primary key constraint"
    events_name_key
    "unique or primary key constraint"
    events_pkey
}

"select columns of table \"events\""
enum events_select_column {
    "column name"
    id
    "column name"
    name
}

"update columns of table \"events\""
enum events_update_column {
    "column name"
    id
    "column name"
    name
}

"column ordering options"
enum order_by {
    "in ascending order, nulls last"
    asc
    "in ascending order, nulls first"
    asc_nulls_first
    "in ascending order, nulls last"
    asc_nulls_last
    "in descending order, nulls first"
    desc
    "in descending order, nulls first"
    desc_nulls_first
    "in descending order, nulls last"
    desc_nulls_last
}

"unique or primary key constraints on table \"protocolTypes\""
enum protocolTypes_constraint {
    "unique or primary key constraint"
    protocolTypes_pkey
}

enum ProtocolTypes_enum {
    Item1
    Item2
    Item3
}

"select columns of table \"protocolTypes\""
enum protocolTypes_select_column {
    "column name"
    type
}

"update columns of table \"protocolTypes\""
enum protocolTypes_update_column {
    "column name"
    type
}

"unique or primary key constraints on table \"protocols\""
enum protocols_constraint {
    "unique or primary key constraint"
    protocols_pkey
}

"select columns of table \"protocols\""
enum protocols_select_column {
    "column name"
    fileUrl
    "column name"
    id
    "column name"
    name
    "column name"
    type
}

"update columns of table \"protocols\""
enum protocols_update_column {
    "column name"
    fileUrl
    "column name"
    id
    "column name"
    name
    "column name"
    type
}

scalar uuid

"Boolean expression to compare columns of type \"String\". All fields are combined with logical 'AND'."
input String_comparison_exp {
    _eq: String
    _gt: String
    _gte: String
    "does the column match the given case-insensitive pattern"
    _ilike: String
    _in: [String!]
    "does the column match the given POSIX regular expression, case insensitive"
    _iregex: String
    _is_null: Boolean
    "does the column match the given pattern"
    _like: String
    _lt: String
    _lte: String
    _neq: String
    "does the column NOT match the given case-insensitive pattern"
    _nilike: String
    _nin: [String!]
    "does the column NOT match the given POSIX regular expression, case insensitive"
    _niregex: String
    "does the column NOT match the given pattern"
    _nlike: String
    "does the column NOT match the given POSIX regular expression, case sensitive"
    _nregex: String
    "does the column NOT match the given SQL regular expression"
    _nsimilar: String
    "does the column match the given POSIX regular expression, case sensitive"
    _regex: String
    "does the column match the given SQL regular expression"
    _similar: String
}

"Boolean expression to filter rows from the table \"events\". All fields are combined with a logical 'AND'."
input events_bool_exp {
    _and: [events_bool_exp!]
    _not: events_bool_exp
    _or: [events_bool_exp!]
    id: uuid_comparison_exp
    name: String_comparison_exp
}

"input type for inserting data into table \"events\""
input events_insert_input {
    id: uuid
    name: String
}

"on_conflict condition type for table \"events\""
input events_on_conflict {
    constraint: events_constraint!
    update_columns: [events_update_column!]! = []
    where: events_bool_exp
}

"Ordering options when selecting data from \"events\"."
input events_order_by {
    id: order_by
    name: order_by
}

"primary key columns input for table: events"
input events_pk_columns_input {
    id: uuid!
}

"input type for updating data in table \"events\""
input events_set_input {
    id: uuid
    name: String
}

"Boolean expression to filter rows from the table \"protocolTypes\". All fields are combined with a logical 'AND'."
input protocolTypes_bool_exp {
    _and: [protocolTypes_bool_exp!]
    _not: protocolTypes_bool_exp
    _or: [protocolTypes_bool_exp!]
    type: String_comparison_exp
}

"Boolean expression to compare columns of type \"ProtocolTypes_enum\". All fields are combined with logical 'AND'."
input ProtocolTypes_enum_comparison_exp {
    _eq: ProtocolTypes_enum
    _in: [ProtocolTypes_enum!]
    _is_null: Boolean
    _neq: ProtocolTypes_enum
    _nin: [ProtocolTypes_enum!]
}

"input type for inserting data into table \"protocolTypes\""
input protocolTypes_insert_input {
    type: String
}

"on_conflict condition type for table \"protocolTypes\""
input protocolTypes_on_conflict {
    constraint: protocolTypes_constraint!
    update_columns: [protocolTypes_update_column!]! = []
    where: protocolTypes_bool_exp
}

"Ordering options when selecting data from \"protocolTypes\"."
input protocolTypes_order_by {
    type: order_by
}

"primary key columns input for table: protocolTypes"
input protocolTypes_pk_columns_input {
    type: String!
}

"input type for updating data in table \"protocolTypes\""
input protocolTypes_set_input {
    type: String
}

"Boolean expression to filter rows from the table \"protocols\". All fields are combined with a logical 'AND'."
input protocols_bool_exp {
    _and: [protocols_bool_exp!]
    _not: protocols_bool_exp
    _or: [protocols_bool_exp!]
    fileUrl: String_comparison_exp
    id: uuid_comparison_exp
    name: String_comparison_exp
    type: ProtocolTypes_enum_comparison_exp
}

"input type for inserting data into table \"protocols\""
input protocols_insert_input {
    fileUrl: String
    id: uuid
    name: String
    type: ProtocolTypes_enum
}

"on_conflict condition type for table \"protocols\""
input protocols_on_conflict {
    constraint: protocols_constraint!
    update_columns: [protocols_update_column!]! = []
    where: protocols_bool_exp
}

"Ordering options when selecting data from \"protocols\"."
input protocols_order_by {
    fileUrl: order_by
    id: order_by
    name: order_by
    type: order_by
}

"primary key columns input for table: protocols"
input protocols_pk_columns_input {
    id: uuid!
}

"input type for updating data in table \"protocols\""
input protocols_set_input {
    fileUrl: String
    id: uuid
    name: String
    type: ProtocolTypes_enum
}

"Boolean expression to compare columns of type \"uuid\". All fields are combined with logical 'AND'."
input uuid_comparison_exp {
    _eq: uuid
    _gt: uuid
    _gte: uuid
    _in: [uuid!]
    _is_null: Boolean
    _lt: uuid
    _lte: uuid
    _neq: uuid
    _nin: [uuid!]
}
```

**Comment by mazaycheck** [comment]
I can confirm this issue still exists, and its quite annoying, first i had to spend mutiple hours to figure out why the code was not generating, there is no errors or any clue why its not working. Second i had to rename all the enum reference in the project. After this it worked.

**Comment by PascalSenn** [comment]
@mazaycheck  what version are you on?

**Comment by mazaycheck** [comment]
So the only workaround i found - is to rename all enum types in your schema.graphql to scalar and remove all the enum cases, and just work with raw string values from there. But i think it is an ugly solution.

**Comment by mazaycheck** [comment]
Hi @PascalSenn, can you help with this issue? Would really appreciate if you have any advice.

**Comment by michaelstaib** [comment]
We will soon shift focus back to StrawberryShake 13 and then look at this issue.
