### ISSUE TITLE
Schema-First Server, With a Query with an Output Object which has an Interface Property

### ISSUE THREAD

**Issue by alex-leroux** [ChilliCream/hotchocolate#4332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error:
1. Unable to resolve dependencies None: Base, Output: Base for type `SimpleObject`. (HotChocolate.Types.ObjectType)

### Steps to reproduce

I create a Schema-First server, with a query with an output object which has an interface property.
This is the schema:

﻿schema {
  query: Query
}

type Query {
  retrieveObjectWithPolymorphicPropertyType(textProperty: String integerProperty: Int!): ObjectWithPolymorphicPropertyTypes
}

type SimpleObject implements Base {
  textProperty: String
  integerProperty: Int!
}

type ObjectWithPolymorphicPropertyTypes {
  interfaceProperty: Base
}

interface Base {
  textProperty: String
  integerProperty: Int!
}

I bind it like this:

        public void ConfigureServices(IServiceCollection services)
        {
            string graphQLSchemaText = LoadSchema();

            services.AddRouting()
                .AddGraphQLServer()
                    .AddDocumentFromString(graphQLSchemaText)

                    .AddResolver<Query>()
                    .BindRuntimeType<SimpleObject>();
        }

My Query handler:

    public class Query
    {
        public ObjectWithPolymorphicPropertyType retrieveObjectWithPolymorphicPropertyType(string textProperty, int integerProperty)
        {
            return AbstractRepository.RetrieveObjectWithPolymorphicPropertyType(textProperty, integerProperty);
        }
    }

And my models:

    [InterfaceType]
    public interface Base
    {
        string textProperty { get; set; }
        int integerProperty { get; set; }
    }

    public class SimpleObject : Base
    {
        public string textProperty { get; set; }
        public int integerProperty { get; set; }
    }

    public class ObjectWithPolymorphicPropertyType
    {
        public Base interfaceProperty { get; set; }
    }

When I launch and try to retrieve the schema (/grapql?sdl), I get the error.
How do I resolve the Base interface type?

### Relevant log output

```shell
An unhandled exception occurred while processing the request.
SchemaException: For more details look at the `Errors` property.

1. Unable to resolve dependencies None: Base, Output: Base for type `SimpleObject`. (HotChocolate.Types.ObjectType)
HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()

Stack Query Cookies Headers Routing
SchemaException: For more details look at the `Errors` property. 1. Unable to resolve dependencies None: Base, Output: Base for type `SimpleObject`. (HotChocolate.Types.ObjectType)
HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
HotChocolate.Configuration.TypeInitializer.CompleteTypes()
HotChocolate.Configuration.TypeInitializer.Initialize(Func<ISchema> schemaResolver, IReadOnlySchemaOptions options)
HotChocolate.SchemaBuilder+Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList<ITypeReference> types, LazySchema lazySchema)
HotChocolate.SchemaBuilder+Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
HotChocolate.AspNetCore.HttpGetSchemaMiddleware.HandleRequestAsync(HttpContext context)
HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
HotChocolate.AspNetCore.HttpMultipartMiddleware.InvokeAsync(HttpContext context)
HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Product

Hot Chocolate

### Version

12.0.1

**Comment by michaelstaib** [comment]
This is now fixed and will be included in 12.7.0-preview.4

**Comment by husseinraoouf** [comment]
I have the same issue and it still happen on 12.7.0 and 12.8.0 preview but it got fixed on 13.0.0, does this mean it won't be on 12.x?

I just don't won't to use previews now for this single issue, i even could help in back porting it to 12.x if you want
