### ISSUE TITLE
Deferred fields on an object within a list are executed sequentially

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#4485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using @defer on a field part of an object type within a list, each deferred field will be executed one after the other. They are not parallelized, like they would be without the @defer.
~~When using @defer on a field within a list that is being resolved by a DataLoader, each item within that list is triggers a batch execution, contrary to how it normally would only trigger one for the entire list~~. 

```graphql
{
  list {
    ... @defer {
      value
    }
  }
}
```

~~If the list resolver returns 3 items, the BatchDataLoader will be invoked 3 times for each item. It only happens if the key is different. if all of the field resolvers use the same key it works as expected.~~

### Steps to reproduce

1. Clone [the repository](https://github.com/tobias-tengler/hc-defer-dataloader-issue)  or just [quickly checkout the code online](https://github.dev/tobias-tengler/hc-defer-dataloader-issue/blob/main/Program.cs)
2. Start the server
3. Execute the following query
```graphql
{
  wrappers {
    value
  }
}
```
Notice how it takes 2.5 seconds and all values pop in at once.
4. Execute the following query
```graphql
{
  wrappers {
    ... @defer {
      value
    }
  }
}
```
Notice how each value pops in one by one, each after 2.5 seconds

### Product

Hot Chocolate

### Version

12.3.2

**Comment by tobias-tengler** [comment]
Okay this isn't even related to the DataLoader. The issue actually is that each defered field is executed one after the other for each item in the list.
I've updated the repro.

**Comment by tobias-tengler** [comment]
This issue isn't exclusive to items within a list, it also happens with two fields on a simple object type as reported [here](https://github.com/ChilliCream/hotchocolate/issues/4491#issuecomment-981079369).

**Comment by michaelstaib** [comment]
This one is fixed and merged into the execution engine branch.
https://github.com/ChilliCream/hotchocolate/pull/5168

**Comment by tobias-tengler** [comment]
The still issue still happens in the latest version (13.0.0-preview.33). It might be the same transport issue as the one causing what I described in https://github.com/ChilliCream/hotchocolate/issues/4491#issuecomment-1228278372

**Comment by tobias-tengler** [comment]
Can confirm it also happens with 13.0.0-preview.47.

This is the minimal reproduction:

```csharp
public class Query
{
    public List<Wrapper> GetWrappers() => new()
    {
        new Wrapper { Id = 1 },
        new Wrapper { Id = 2 },
        new Wrapper { Id = 3 }
    };
}

public class Wrapper
{
    public int Id { get; set; }

    public async Task<string> GetValueAsync([Parent] Wrapper wrapper)
    {
        //await Task.Yield();

        var wait = wrapper.Id == 1 ? 1000 : 5000;
        await Task.Delay(wait);

        return $"MyValue:{wrapper.Id}:{wait}";
    }
}
```

This is the query I used:

```graphql
{
  wrappers {
    id
    ... @defer {
      value
    }
  }
}
```
