### ISSUE TITLE
Regression in sharing types between stitching and resolvers

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#4520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We're seeing a regression in behavior updating our stitching gateways from Hot Chocolate 11 to 12.

These gateways primarily stitch in other services but do have some resolvers hosted at the gateway themselves. Thera are some shared types that are stitched in but also used in those gateway resolvers.

For this we have some setup code to bind the CLR type to the stitched types.
``` csharp
.BindComplexType<ValidationErrors>(b => b.To(nameof(ValidationErrors)))
.BindComplexType<RegularExpressionValidationError>(b => b.To(nameof(RegularExpressionValidationError)))
.BindComplexType<StringLengthValidationError>(b => b.To(nameof(StringLengthValidationError)))
```

While updating to HC 12 I updated that code to 
``` csharp
.BindRuntimeType<ValidationErrors>()
.BindRuntimeType<RegularExpressionValidationError>()
.BindRuntimeType<StringLengthValidationError>()
```

and saw this error on schema creation.
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at void HotChocolate.Types.TypeSystemObjectBase.MarkNamed()
   at void HotChocolate.Types.TypeSystemObjectBase.CompleteName(ITypeCompletionContext context)
   at void HotChocolate.Types.ScalarType.CompleteName(ITypeCompletionContext context)
 ```
 
A few extra details, I did have `InitializeOnStartup` has part of setup but this isn't working, I'm seeing the above exception on first request.  Turning off `InitializeOnStartup` changes the exception to 

```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve dependencies None: CostDirectiveType, None: IValidationError, None: source, None: source, None: source, None: source, Output: IValidationError for type `StringLengthValidationError`. (HotChocolate.Types.ObjectType)
```

### Steps to reproduce

1.  Have a stitched gateway with some common types.
2. Have resolvers use those same CLR types.
3. Bind the CLR type to the stitched type.

### Relevant log output

```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve dependencies None: CostDirectiveType, None: IValidationError, None: source, None: source, None: source, None: source, Output: IValidationError for type `StringLengthValidationError`. (HotChocolate.Types.ObjectType)
```

### Product

Hot Chocolate

### Version

12.3.1

### Update
One piece of information I forgot to add was that it seems to be combination of lines of `BindRuntimeType`. If only a single line was included then the schema will create (but the field that uses those types fails), 

It's only when there's more than one type being bound with `BindRuntimeType` do we see the errros.

**Comment by nigel-sampson** [comment]
It looks like I'm able to work around this by creating merge rules to stop these types being merged in from the stitched gateways and then added back in via `AddType` instead of `BindRuntimeType`.

While it works it makes working with any of these types across the services in the gateway a lot more fragile.

**Comment by michaelstaib** [comment]
I have put it to the 12.5 backlog.

**Comment by nigel-sampson** [comment]
Thank you.

**Comment by nigel-sampson** [comment]
I've pushed a small reproduction of the problem to https://github.com/nigel-sampson/hc-reproductions/tree/main/4520/BindMergeTypes

The absolution simple scenario where it's a single type looks to be working correctly.  Initially I had a single type shared across the service and the gateway where the gateway used `[GraphQLType("Person!")]` and this worked correctly.

I expanded the scenario to something closer to the problem we're seeing and am seeing the same problem. Given the simple problem works correctly and a single `BindRuntimeType` works well it seems the regression is when there's a a dependency chain between two types which are being shared across the service and the gateway.

If there's anything else that's needed or you'd like me to experiment with let me know.

**Comment by gmiserez** [comment]
> I have put it to the 12.5 backlog.

The issue is still present with 12.6 apprently. After removing `InitializeOnStartup()` I'm getting:

`1. Unable to resolve type reference `None: Uuid!`. (HotChocolate.Types.ObjectType)`

**Comment by michaelstaib** [comment]
Hey Gilles,

do we have a problem with fusion?

**Comment by gmiserez** [comment]
Yeah, I'm currently migrating our stitching Api to HC 12 and ran into this problem.

**Comment by Blue4x4Rebel** [comment]
I'm seeing a very similar issue. No resolvers on the gateway, but we had to explicity add some types:
`
 services
       .AddGraphQLServer()
       .AddRemoteSchemasFromRedis(SchemaName, sp =>
	       sp.GetRequiredService<IConnectionMultiplexer>())
       .AddType<UnsignedShortType>();
builder.Services
       .AddGraphQL(ActionsSubgraph).AddType(new AnyType("UnsignedShort"));
`

Anytime the subgraph service is updated, the gateway responds with:
  _Operation is not valid due to the current state of the object._

**Comment by Spaier** [comment]
Have the same issue as @Blue4x4Rebel in HotChocolate 12.12.1 
Will it be fixed only in HotChocolate 13?

```
 services
       .AddGraphQLServer()
       .AddRemoteSchemasFromRedis(SchemaName, sp =>
	       sp.GetRequiredService<IConnectionMultiplexer>())
       .AddType(new AnyType("Seconds"));
builder.Services
       .AddGraphQL(ActionsSubgraph).AddType(new AnyType("Seconds"));
```

```
HotChocolate.SchemaException: For more details look at the `Errors` property.\r\n\r\n1. Operation is not valid due to the current state of the object. (HotChocolate.Types.AnyType)\r\n\r\n   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()\r\n   at HotChocolate.Configuration.TypeInitializer.Initialize()\r\n   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)\r\n   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)\r\n   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)\r\n   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)\r\n   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)\r\n   at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass5_0.<<AddRemoteSchema>b__2>d.MoveNext()\r\n
```

**Comment by chris-findlay** [comment]
+1 for the above question..
